services:
  sre-log-triage:
    build: .
    container_name: sre-log-triage-dashboard
    ports:
      - "8443:8000"
    volumes:
      - ./app.db:/app/app.db
      - ./certs:/app/certs:ro
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--ssl-keyfile",
        "/app/certs/localhost-key.pem",
        "--ssl-certfile",
        "/app/certs/localhost.pem"
      ]